# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50)),
                ('view', models.CharField(choices=[('list', 'List View'), ('edit', 'Edit View'), ('create', 'Create View')], max_length=30)),
                ('fields', models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='layout',
            unique_together=set([('module', 'view')]),
        ),
    ]
