# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-02 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_userattr'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattr',
            name='user_type',
            field=models.CharField(choices=[('single', b'Usuario individual'), ('account', 'Account')], default='single', max_length=30),
        ),
    ]
