# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-03 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_userattr_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattr',
            name='user_type',
            field=models.CharField(choices=[('single', 'Single'), ('account', 'Account')], default='single', max_length=30),
        ),
    ]
